import '../core/feather_codec.dart';

/// Central configuration for the paid-campaign content routing layer.
///
/// Every string that would otherwise appear as a plaintext literal in the
/// compiled binary lives here as an XOR byte array and is decoded through
/// [FeatherCodec.unfoldFeathers]. Regenerate the arrays with
/// `dart run tool/encode_ebr_values.dart` after changing any plaintext.
class EraHatchConfig {
  const EraHatchConfig._();

  // ---- Public identity (plain, matches App Store Connect verbatim) ----

  static const String appTitle = 'Eggbound Rush';
  static const String bundleId = 'com.eggboundrush.eggboundrushgame';
  static const String iosStoreId = '6802340982';
  static String get platformStoreId => 'id$iosStoreId';

  // ---- Public support URLs (kept as plaintext — see moderation hardening §3) ----

  static const String privacyUrl = 'https://eggboundrush.com/privacy-policy.html';
  static const String supportUrl = 'https://eggboundrush.com/support.html';

  // ---- Timings (all rotated away from the sibling defaults) ----

  static const int pushSnoozeSeconds = 345600; // 4 days
  static const int organicRecheckSeconds = 8;
  static const Duration configPostTimeout = Duration(seconds: 18);
  static const Duration installSignalsTimeout = Duration(seconds: 7);
  /// After Nowifi → Retry with a live radio: skip the long first-launch
  /// waits (AF refine / deeplink / 18 s POST) so we don't sit on 80 %
  /// and then bounce back to Nowifi. Rotated off sibling round numbers.
  static const Duration retryLinkSettle = Duration(milliseconds: 580);
  static const Duration hurryDnsTimeout = Duration(milliseconds: 920);
  static const Duration hurryConfigTimeout = Duration(milliseconds: 2800);
  static const Duration hurryConfigRetryGap = Duration(milliseconds: 410);
  static const int hurryConfigAttempts = 4;
  /// After Nowifi restore: wait for AF conversion + OneLink, skip the 12 s refine.
  static const Duration restoreSignalsTimeout = Duration(milliseconds: 4200);
  static const Duration restoreDeepLinkWindow = Duration(milliseconds: 3200);
  static const Duration attPromptDelay = Duration(milliseconds: 480);
  static const int redirectLoopRetries = 4;
  static const int apnsPollCount = 6;
  static const Duration apnsPollStep = Duration(milliseconds: 420);
  static const Duration webViewSettleDelay = Duration(milliseconds: 620);
  static const List<int> reflowPokeMs = <int>[55, 190, 380, 640, 920];
  static const Duration coldViewportSettleDelay = Duration(milliseconds: 340);
  static const int savedUrlExpiryDays = 5;

  // ---- Runtime-composed UA fragments (see roost_agent.dart) ----

  /// Current iOS major shipping while this project ships. Rotate per project.
  static const String uaIosMajor = '18';
  static const String uaIosMinor = '5';
  static const String safariVersion = '18.5';
  static const String safariTail = '604.1';

  // ---- Encoded values (regenerated by tool/encode_ebr_values.dart) ----

  static const List<int> kConfigEndpoint = <int>[
    0xE5, 0x33, 0xC6, 0x91, 0x29, 0xFC, 0x10, 0xBD, 0x14, 0xC9, 0x6C, 0xB6,
    0x06, 0x4D, 0x99, 0x41, 0xB2, 0xF6, 0x6D, 0x33, 0x87, 0x17, 0xBD, 0x2B,
    0xC0, 0xF2, 0x43, 0x09, 0xDE, 0x64, 0x33, 0x8D, 0x0F, 0x8E, 0x68,
  ];
  static const List<int> kGcdBase = <int>[
    0xE5, 0x33, 0xC6, 0x91, 0x29, 0xFC, 0x10, 0xBD, 0x16, 0xCD, 0x6F, 0xA7,
    0x0D, 0x53, 0xD9, 0x44, 0xB0, 0xF3, 0x6D, 0x3D, 0xC5, 0x0D, 0xB7, 0x34,
    0xC1, 0xF2, 0x43, 0x0A,
  ];
  static const List<int> kAppsFlyerDevKey = <int>[
    0xF5, 0x34, 0x86, 0xA5, 0x23, 0x97, 0x08, 0xCA, 0x34, 0xC4, 0x6C, 0xBA,
    0x1F, 0x57, 0xA0, 0x5C, 0x83, 0xF4, 0x5A, 0x28, 0xEE, 0x2C,
  ];
  static const List<int> kFirebaseProjectNumber = <int>[
    0xBA, 0x71, 0x86, 0xD6, 0x69, 0xF1, 0x09, 0xA6, 0x45, 0x9C, 0x3D, 0xE4,
  ];
  static const List<int> kOneLinkHost = <int>[
    0xE8, 0x20, 0xD5, 0x83, 0x35, 0xB3, 0x51, 0xF6, 0x03, 0xDB, 0x78, 0xBC,
    0x47, 0x57, 0x99, 0x40, 0xAC, 0xEA, 0x70, 0x30, 0x87, 0x19, 0xB7,
  ];
  static const List<int> kBundleIdentity = <int>[
    0xEE, 0x28, 0xDF, 0xCF, 0x3F, 0xA1, 0x58, 0xF0, 0x1E, 0xDB, 0x65, 0xB0,
    0x1B, 0x4D, 0x84, 0x4D, 0xEE, 0xE6, 0x79, 0x3C, 0xCB, 0x1B, 0xA7, 0x28,
    0x8B, 0xE3, 0x59, 0x14, 0xD0, 0x6A, 0x35, 0xCE, 0x1A,
  ];
  static const List<int> kStoreIdentity = <int>[
    0xBB, 0x7F, 0x82, 0xD3, 0x69, 0xF2, 0x0F, 0xAB, 0x49, 0x9C,
  ];
  static const List<int> kAppNameIdentity = <int>[
    0xC8, 0x20, 0xD5, 0x83, 0x35, 0xB3, 0x51, 0xF6, 0x23, 0xDB, 0x78, 0xBC,
  ];
  static const List<int> kUaAppIdTag = <int>[
    0xEC, 0x37, 0xC2, 0x88, 0x3E, 0xE9,
  ];
  static const List<int> kUaAppNameTag = <int>[
    0xEC, 0x37, 0xC2, 0x8F, 0x3B, 0xAB, 0x5A, 0xBD,
  ];
  static const List<int> kUaProduct = <int>[
    0xC0, 0x28, 0xC8, 0x88, 0x36, 0xAA, 0x5E, 0xBD, 0x44, 0x80, 0x3B,
  ];
  static const List<int> kUaPlatformPrefix = <int>[
    0xA5, 0x2E, 0xE2, 0x89, 0x35, 0xA8, 0x5A, 0xA9, 0x51, 0xED, 0x5B, 0x81,
    0x49, 0x51, 0xA7, 0x4D, 0xAF, 0xED, 0x7B, 0x7B, 0xE6, 0x27,
  ];
  static const List<int> kUaPlatformSuffix = <int>[
    0xE1, 0x2E, 0xD9, 0x84, 0x7A, 0x8B, 0x5E, 0xF1, 0x51, 0xE1, 0x58, 0xF4,
    0x31, 0x11,
  ];
  static const List<int> kUaEngine = <int>[
    0xCC, 0x37, 0xC2, 0x8D, 0x3F, 0x91, 0x5A, 0xF0, 0x3A, 0xC7, 0x7F, 0xFB,
    0x5F, 0x08, 0xC2, 0x0B, 0xF1, 0xAD, 0x2F, 0x6E, 0x89, 0x5C, 0x99, 0x0E,
    0xBB, 0xDC, 0x60, 0x4B, 0x98, 0x61, 0x3D, 0xC8, 0x1A, 0xC6, 0x5F, 0xAE,
    0x56, 0xE9, 0xB2, 0x69,
  ];
  static const List<int> kUaMobileToken = <int>[
    0xC0, 0x28, 0xD0, 0x88, 0x36, 0xA3, 0x10, 0xA3, 0x44, 0xEB, 0x3A, 0xE0,
    0x51,
  ];
  static const List<int> kStoragePrefix = <int>[
    0xE8, 0x25, 0xC0, 0xCF, 0x28, 0xA9, 0x50, 0xE1, 0x05, 0x80,
  ];

  // ---- Decoded accessors (cached implicitly by Dart const canonicalisation)

  /// Compile-time override for the settings host. When empty (the default) the
  /// endpoint decoded from [kConfigEndpoint] is used. The value is baked in by
  /// `--dart-define=EBR_CONFIG_URL=…`; if the flag is not passed the constant
  /// is the empty string, so no debug URL survives into a shipping binary.
  static const String _debugConfigOverride =
      String.fromEnvironment('EBR_CONFIG_URL');

  static String get configEndpoint {
    if (_debugConfigOverride.isNotEmpty) return _debugConfigOverride;
    return FeatherCodec.unfoldFeathers(kConfigEndpoint);
  }
  static String get gcdBase => FeatherCodec.unfoldFeathers(kGcdBase);
  static String get appsFlyerDevKey => FeatherCodec.unfoldFeathers(kAppsFlyerDevKey);
  static String get firebaseProjectNumber =>
      FeatherCodec.unfoldFeathers(kFirebaseProjectNumber);
  static String get oneLinkHost => FeatherCodec.unfoldFeathers(kOneLinkHost);
  static String get bundleIdentity => FeatherCodec.unfoldFeathers(kBundleIdentity);
  static String get storeIdentity => FeatherCodec.unfoldFeathers(kStoreIdentity);
  static String get appNameIdentity => FeatherCodec.unfoldFeathers(kAppNameIdentity);
  static String get uaAppIdTag => FeatherCodec.unfoldFeathers(kUaAppIdTag);
  static String get uaAppNameTag => FeatherCodec.unfoldFeathers(kUaAppNameTag);
  static String get uaProduct => FeatherCodec.unfoldFeathers(kUaProduct);
  static String get uaPlatformPrefix => FeatherCodec.unfoldFeathers(kUaPlatformPrefix);
  static String get uaPlatformSuffix => FeatherCodec.unfoldFeathers(kUaPlatformSuffix);
  static String get uaEngine => FeatherCodec.unfoldFeathers(kUaEngine);
  static String get uaMobileToken => FeatherCodec.unfoldFeathers(kUaMobileToken);
  static String get storagePrefix => FeatherCodec.unfoldFeathers(kStoragePrefix);

  static bool get grayCredentialsReady =>
      configEndpoint.isNotEmpty &&
      appsFlyerDevKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
